# Generated by Django 4.0 on 2022-01-05 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_productinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
